name: build
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        description: 'NPM token to use to publish packages'
        required: false
    inputs:
      version:
        description: 'Version number (x.y.z) to set before executing the build'
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run format
      - run: npm run lint -- --quiet
      - run: npm run check
      - run: npm run test
      - run: npm run coverage
      - uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info
          flags: unit
          disable_search: true
          threshold: -3.02%
          use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
      - run: npm run build

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
