name: ci
on:
  push:
    branches: [main, release/**]

jobs:
  build:
    uses: './.github/workflows/build.yml'
    with:
      version: ${{ github.ref_name }}
  validate-os:
    uses: './.github/workflows/validate-os.yml'
